server:
  port: ${QUOTES_SERVICE_PORT:8082}

user.service.host: ${USER_SERVICE_HOST:localhost}
user.service.port: ${USER_SERVICE_PORT:8081}
user.service.path: ${USER_SERVICE_PATH:/api/v1/users}

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: username1
    password: password1
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
